name: myworkflow
on: 
   push:
     branches: [ main ]
jobs:  
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Set Environment Variables
      uses: ./.github/actions/setvars
      with:
        varFilePath: ./.github/variables/myvars.env
