name: Reusable workflow

on:
  workflow_dispatch:
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@hirenrparghi"
      - name: check
        run: |
          ls -la
      - name: Configure NPM
        run: |
          npm config set '//npm.pkg.github.com/:_authToken' "${{secrets.GITHUB_TOKEN}}"          
          npm install @hirenrparghi/npm-publish@8.9.9
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   
      - name: show package    
        run: |
           ls -la
           
