name: Reusable workflow

on:
  workflow_dispatch:
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: download published package
        if: always()
        run: |          
          curl -u ${{ secrets.GITHUB_TOKEN }} -L \
           -o Modules.zip \
           https://github.com/hirenrparghi/packages/@hirenrparghi/npm-publish@6.9.9/Modules.zip
          ls -la
          
      - name: check package
        if: always()
        run : |
          pwd
          ls -la 
