name: myworkflow
on: 
   push:
     branches: [ main ]
jobs:  
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Set Environment Variables
      run : |
        echo "value=$(date)" >> $GITHUB_ENV
    - name: get env
      run: |
       echo "${{ env.value }}"
      
