name: Reusable workflow

on:
  workflow_dispatch:
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: download published package
        if: always()
        run: |          
          curl -u hirenrparghi:${{secrets.GITHUB_TOKEN}} -L -O npm-publish-2.9.9.tgz "https://npm.pkg.github.com/hirenrparghi/npm-publish/-/1.9.9/npm-publish-2.9.9.tar.gz"
          tar -xzf npm-publish-2.9.9.tar.gz          
          
      - name: check package
        if: always()
        run : |
          pwd
          ls -la 
