name: myworkflow
on: 
   push:
     branches: [ main ]
jobs:  
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Set Environment Variables
      uses: actions/checkout@v2
      with:
        varFilePath: ./.github/variables/myvars.env
    - name: fetch env
      run : echo ${ env.MYVAR1 }
      
