name: Reusable workflow

on:
  workflow_call:

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - name: download published package
        if: always()
        run: |
          npm config set @hirenrparghi:registry https://npm.pkg.github.com
          npm i @hirenrparghi/npm-publish@1.0.4
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
      - name: check package
        run : |
          pwd
          ls -la 
